### ISSUE TITLE
[rank0]: KeyError: 'answer'

### ISSUE THREAD

**Issue by lucasjinreal** [open-compass/VLMEvalKit#268] opened 2024-07-10 06:33 UTC
/vlmeval/dataset/image_mcq.py", line 181, in evaluate
[rank0]:     answer_map = {i: c for i, c in zip(meta['index'], meta['answer'])}
[rank0]:   File "/data/miniconda3/envs/env-3.9.2/lib/python3.9/site-packages/pandas/core/frame.py", line 4102, in __getitem__
[rank0]:     indexer = self.columns.get_loc(key)
[rank0]:   File "/data/miniconda3/envs/env-3.9.2/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
[rank0]:     raise KeyError(key) from err
[rank0]: KeyError: 'answer'

**Comment by junming-yang** [comment] 2024-07-10 06:39
Can you provide the running command?

**Comment by junming-yang** [comment] 2024-07-12 04:08
If you are evaluating a private benchmark, please check your dataset file `xxx. tsv` fields correct, such as 'answer' instead of 'ans'. Please refer to [Development Doc](https://github.com/open-compass/VLMEvalKit/blob/main/docs/en/Development.md) for More detailed information.

**Comment by lucasjinreal** [comment] 2024-07-12 06:14
Am runing on MME only got this error

**Comment by junming-yang** [comment] 2024-07-12 06:47
I try to reproduce this error. This is my command `torchrun --nproc-per-node=8 run.py --model InternVL-Chat-V1-5 --data MME`. Everything is OK. And **MME** benchmark should correspond to the `image_yorn.py` file instead of `image_mcq.py`. Please check your code repo.

**Comment by lucasjinreal** [comment] 2024-07-12 07:00
Then that's weired, I didn touched anything inside vlmkit, those tsv are automatically downloaded, there must be an key error at some where in some dataset.

**Comment by junming-yang** [comment] 2024-07-12 07:08
Maybe you can try to pull our latest code. We have fixed some known minor bugs. If you still encounter other problems, please do not hesitate to contact us and give us some detailed information to fix them. Thank you.

**Comment by kennymckormick** [comment] 2024-07-18 10:57
Hi, @lucasjinreal , I tried to reproduce the problem but failed (I'm evaluating llava_v1.5_7b on MME), with latest main branch.

**Comment by kennymckormick** [comment] 2024-08-27 12:22
Duplicate of https://github.com/open-compass/VLMEvalKit/issues/378

**Closed by kennymckormick** 2024-08-27 12:22 UTC
